-- MySQL Script generated by MySQL Workbench
-- Fri Jan 19 14:00:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema malluDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `malluDB` ;

-- -----------------------------------------------------
-- Schema malluDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `malluDB` DEFAULT CHARACTER SET utf8 ;
USE `malluDB` ;

-- -----------------------------------------------------
-- Table `malluDB`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `malluDB`.`Professor` ;

CREATE TABLE IF NOT EXISTS `malluDB`.`Professor` (
  `email` VARCHAR(100) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `imgPerfil` VARCHAR(100) NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malluDB`.`Turma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `malluDB`.`Turma` ;

CREATE TABLE IF NOT EXISTS `malluDB`.`Turma` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malluDB`.`Diario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `malluDB`.`Diario` ;

CREATE TABLE IF NOT EXISTS `malluDB`.`Diario` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `disciplina` VARCHAR(100) NOT NULL,
  `escola` VARCHAR(100) NOT NULL,
  `serie` INT NOT NULL,
  `modalidade` ENUM('med', 'fund', 'prim') NOT NULL,
  `Professor_email` VARCHAR(100) NOT NULL,
  `Turma_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Diário_Professor1_idx` (`Professor_email` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Diario_Turma1_idx` (`Turma_id` ASC),
  CONSTRAINT `fk_Diário_Professor1`
    FOREIGN KEY (`Professor_email`)
    REFERENCES `malluDB`.`Professor` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Diario_Turma1`
    FOREIGN KEY (`Turma_id`)
    REFERENCES `malluDB`.`Turma` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malluDB`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `malluDB`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `malluDB`.`Aluno` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `Turma_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Aluno_Turma1_idx` (`Turma_id` ASC),
  CONSTRAINT `fk_Aluno_Turma1`
    FOREIGN KEY (`Turma_id`)
    REFERENCES `malluDB`.`Turma` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malluDB`.`PeriodoRegime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `malluDB`.`PeriodoRegime` ;

CREATE TABLE IF NOT EXISTS `malluDB`.`PeriodoRegime` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataInicio` DATE NOT NULL,
  `dataFim` DATE NOT NULL,
  `qntAulas` INT NOT NULL,
  `valorTotal` INT NOT NULL COMMENT 'identifica qual o valor do período referido, que servirá para base de notas das disciplinas',
  `Diario_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_PeriodoDeRegime_Diario1_idx` (`Diario_id` ASC),
  CONSTRAINT `fk_PeriodoDeRegime_Diario1`
    FOREIGN KEY (`Diario_id`)
    REFERENCES `malluDB`.`Diario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malluDB`.`Aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `malluDB`.`Aula` ;

CREATE TABLE IF NOT EXISTS `malluDB`.`Aula` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `data` DATE NOT NULL,
  `PeriodoRegime_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Aula_PeriodoRegime1_idx` (`PeriodoRegime_id` ASC),
  CONSTRAINT `fk_Aula_PeriodoRegime1`
    FOREIGN KEY (`PeriodoRegime_id`)
    REFERENCES `malluDB`.`PeriodoRegime` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malluDB`.`Avaliacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `malluDB`.`Avaliacao` ;

CREATE TABLE IF NOT EXISTS `malluDB`.`Avaliacao` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tema` VARCHAR(100) NOT NULL,
  `valor` INT NOT NULL,
  `data` DATE NOT NULL,
  `PeriodoRegime_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Avaliacao_PeriodoRegime1_idx` (`PeriodoRegime_id` ASC),
  CONSTRAINT `fk_Avaliacao_PeriodoRegime1`
    FOREIGN KEY (`PeriodoRegime_id`)
    REFERENCES `malluDB`.`PeriodoRegime` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malluDB`.`Chamada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `malluDB`.`Chamada` ;

CREATE TABLE IF NOT EXISTS `malluDB`.`Chamada` (
  `Aula_id` BIGINT UNSIGNED NOT NULL,
  `Aluno_id` BIGINT UNSIGNED NOT NULL,
  `presenca` TINYINT NOT NULL,
  PRIMARY KEY (`Aula_id`, `Aluno_id`),
  INDEX `fk_Aula_has_Aluno_Aluno1_idx` (`Aluno_id` ASC),
  INDEX `fk_Aula_has_Aluno_Aula1_idx` (`Aula_id` ASC),
  CONSTRAINT `fk_Aula_has_Aluno_Aula1`
    FOREIGN KEY (`Aula_id`)
    REFERENCES `malluDB`.`Aula` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Aula_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_id`)
    REFERENCES `malluDB`.`Aluno` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malluDB`.`Nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `malluDB`.`Nota` ;

CREATE TABLE IF NOT EXISTS `malluDB`.`Nota` (
  `Avaliacao_id` BIGINT UNSIGNED NOT NULL,
  `Aluno_id` BIGINT UNSIGNED NOT NULL,
  `nota` DOUBLE NOT NULL,
  PRIMARY KEY (`Avaliacao_id`, `Aluno_id`),
  INDEX `fk_Avaliacao_has_Aluno_Aluno1_idx` (`Aluno_id` ASC),
  INDEX `fk_Avaliacao_has_Aluno_Avaliacao1_idx` (`Avaliacao_id` ASC),
  CONSTRAINT `fk_Avaliacao_has_Aluno_Avaliacao1`
    FOREIGN KEY (`Avaliacao_id`)
    REFERENCES `malluDB`.`Avaliacao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Avaliacao_has_Aluno_Aluno1`
    FOREIGN KEY (`Aluno_id`)
    REFERENCES `malluDB`.`Aluno` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
